# Generated by Django 4.2.30 on 2026-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MITRETechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technique_id",
                    models.CharField(
                        help_text="MITRE technique ID, e.g., T1059.001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "tactic",
                    models.CharField(
                        choices=[
                            ("reconnaissance", "Reconnaissance"),
                            ("resource_development", "Resource Development"),
                            ("initial_access", "Initial Access"),
                            ("execution", "Execution"),
                            ("persistence", "Persistence"),
                            ("privilege_escalation", "Privilege Escalation"),
                            ("defense_evasion", "Defense Evasion"),
                            ("credential_access", "Credential Access"),
                            ("discovery", "Discovery"),
                            ("lateral_movement", "Lateral Movement"),
                            ("collection", "Collection"),
                            ("command_and_control", "Command and Control"),
                            ("exfiltration", "Exfiltration"),
                            ("impact", "Impact"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "evidence_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of observed events supporting this technique",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unconfirmed", "Unconfirmed"),
                        ],
                        default="unconfirmed",
                        max_length=15,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, default="", help_text="Link to MITRE ATT&CK page"
                    ),
                ),
                (
                    "trigger_evidence",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What evidence triggers this technique mapping",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MITRE Technique",
                "verbose_name_plural": "MITRE Techniques",
                "ordering": ["tactic", "technique_id"],
            },
        ),
    ]
