# Generated by Django 4.2.30 on 2026-10-04 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investigations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("pdf", "PDF")],
                        default="json",
                        max_length=10,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("executive_summary", models.TextField(blank=True, default="")),
                ("detection_summary", models.TextField(blank=True, default="")),
                ("evidence_summary", models.JSONField(blank=True, default=list)),
                ("timeline_summary", models.JSONField(blank=True, default=list)),
                ("mitre_summary", models.JSONField(blank=True, default=list)),
                ("investigation_summary", models.TextField(blank=True, default="")),
                ("findings_summary", models.TextField(blank=True, default="")),
                (
                    "uncertainty",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What could not be confirmed in this investigation",
                    ),
                ),
                ("recommended_actions", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="investigations.investigationcase",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SOC Report",
                "verbose_name_plural": "SOC Reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
