# Generated by Django 4.2.30 on 2026-10-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mitre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuntQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("account_management", "Account Management"),
                            ("execution", "Execution"),
                            ("powershell", "PowerShell"),
                            ("command_shell", "Command Shell"),
                            ("process_creation", "Process Creation"),
                            ("persistence", "Persistence"),
                            ("privilege_escalation", "Privilege Escalation"),
                            ("credential_access", "Credential Access"),
                            ("lateral_movement", "Lateral Movement"),
                            ("collection", "Data Collection"),
                            ("exfiltration", "Exfiltration"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "hypothesis",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The threat hypothesis this hunt tests",
                    ),
                ),
                ("spl", models.TextField(help_text="The SPL query to execute")),
                (
                    "data_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expected_evidence", models.TextField(blank=True, default="")),
                ("investigation_notes", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mitre_technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hunts",
                        to="mitre.mitretechnique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hunt Query",
                "verbose_name_plural": "Hunt Queries",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("spl", models.TextField(help_text="The SPL detection query")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "false_positive_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Known false positive scenarios for this rule",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mitre_technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_rules",
                        to="mitre.mitretechnique",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
