# Generated by Django 4.2.30 on 2026-10-04 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mitre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("closed", "Closed"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dest_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "splunk_query",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The SPL query used to discover this case",
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What was established from the investigation",
                    ),
                ),
                (
                    "recommended_actions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Actions recommended for remediation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_analyst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mitre_techniques",
                    models.ManyToManyField(
                        blank=True, related_name="cases", to="mitre.mitretechnique"
                    ),
                ),
            ],
            options={
                "verbose_name": "Investigation Case",
                "verbose_name_plural": "Investigation Cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "detection_rule",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("event_code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "evidence_raw",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw event data from Splunk"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("unclassified", "Unclassified"),
                            ("true_positive", "True Positive"),
                            ("false_positive", "False Positive"),
                            ("benign", "Benign / Expected"),
                            ("needs_investigation", "Needs More Investigation"),
                        ],
                        default="unclassified",
                        max_length=25,
                    ),
                ),
                (
                    "classification_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this classification was chosen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="investigations.investigationcase",
                    ),
                ),
                (
                    "mitre_techniques",
                    models.ManyToManyField(
                        blank=True, related_name="findings", to="mitre.mitretechnique"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("host", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("event_code", models.CharField(blank=True, default="", max_length=50)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dest_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "process_name",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("command_line", models.TextField(blank=True, default="")),
                (
                    "raw_event",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full raw event from Splunk"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Analyst description of this evidence",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="investigations.investigationcase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evidence",
                "ordering": ["event_time"],
            },
        ),
        migrations.CreateModel(
            name="AnalystNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="investigations.investigationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
